### ISSUE TITLE
Better command handling: DM or not

### ISSUE THREAD

**Issue by horshark** [DarkStar7471/THM-Bot#108]
**Describe the bug**
The command doesn't work in DMs and generates errors.
Eventually, make this so it can be used with other commands as well. 
To be made with: https://github.com/DarkStar7471/THM-Bot/issues/103

**To Reproduce**
1. Go in DMs with the bot.
2. Use the command !notifyme

**Expected behavior**
The command should toggle the role.

**Additional context**
Error:
```
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/BOT_running_v2/cogs/announcementrole.py", line 33, in role_announce
    announceRole = ctx.guild.get_role(id_announcerole)
AttributeError: 'NoneType' object has no attribute 'get_role'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 303, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 77, in on_command_error
    raise error
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 824, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no
 attribute 'get_role'
```

**Comment by horshark** [comment]
Add a command lib that checks for perms/roles, if DM/server is required (default both are okay)
[ ] Roles check
[ ] Context check

**Comment by horshark** [comment]
I'll be making another issue for its progressive implementation to all the cogs.

**Comment by horshark** [comment]
Moved to https://github.com/DarkStar7471/THM-Bot/issues/125
